services:
  db: 
    image: postgres:latest
    container_name: pokemon_db
    restart: always
    environment:
      - POSTGRES_USER=pokemon_db
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pokemon_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
