services:
  db: 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pokemon_db
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pokemon_db
      - POSTGRES_HOST_AUTHMETHOD=trust
    ports:
      - '5432:5432'
